### ISSUE TITLE
When are m3u available?

### ISSUE THREAD

**Issue by Raspifan2020** [LibreIPTV/Countries#1]
Hi,

i has found your repo today. When are m3u available?

Greetings

Raspifan

**Comment by Raspifan2020** [comment]
Hallo, jemand Zuhause? Hat wohl nicht geklappt, mit dem Klauen der Arbeit von Free-IPTV! Das öffentliche Repo beendet, das private Repo für dich NICHT verfügbar! Haha...

**Comment by Yuxael** [comment]
Sorry, haven't got time lately to finish it.
